### ISSUE TITLE
PostData timeout

### ISSUE THREAD

**Issue by dnstommy** [AuthorizeNet/sdk-dotnet#274]
When submitting a payment at the line below, we are getting several timeouts per day. The timeout period is currently at 30 seconds. The customer's credit card is being charged, but since I have no response, I am not able to refund the transaction. I only have the nonce.

https://github.com/AuthorizeNet/sdk-dotnet/blob/master/Authorize.NET/Util/HttpUtility.cs#L32

19760 08:24:45 INFO  Trace: Creating PostRequest Url: 'https://api2.authorize.net/xml/v1/request.api'
19760 08:24:45 INFO  Trace: Retreiving Response from Url: 'https://api2.authorize.net/xml/v1/request.api'
19760 08:24:45 ERROR The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.
Exception: System.Net.WebException
Message: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server.
Source: System
   at System.Net.HttpWebRequest.GetResponse()
   at AuthorizeNet.Util.HttpUtility.PostData[TQ,TS](Environment env, TQ request)
   at AuthorizeNet.Api.Controllers.Bases.ApiOperationBase`2.Execute(Environment environment)

**Comment by RickyBiggz** [comment]
@dnstommy , did you ever get a resolution for this? The only solution I found would be to catch this exception and get the unsettled transactions and use the invoice number to find the transaction if it exists.

**Comment by dnstommy** [comment]
@RickyBiggz the only thing I could do was to catch the error and throw the customer information into a queue for further review.
