### ISSUE TITLE
Issue and Proposed Fix for  :  the type initializer for 'AuthorizeNet.Util.HttpUtility' error

### ISSUE THREAD

**Issue by schandan-ssactivewear** [AuthorizeNet/sdk-dotnet#292]
Hi Team,

We are one of the heavy users of this framework for our retail application .
We see this below issue intermittently  3 or 4 times  a month which blocks the users from checking out . The only way to fix it is restarting the app pool. Until the app pool is restarted out checkout screen breaks
![image](https://user-images.githubusercontent.com/98968474/152376577-e9a000fd-6a9b-4909-a303-2f00cea97ce3.png)

### **Analysis** :
To replicate the issue in lower environment we started hitting the service  from our app while the app is getting recycled or redeployed. (in sandbox)

The HTTPUtility is the entry point class for any API calls that goes to Authorize and it has this Static Properties which invokes the **AuthorizeNet.Envvironment.getBooleanProperty()** 

![image](https://user-images.githubusercontent.com/98968474/152376668-2b4f1647-0c57-4e56-a284-b4b73528c675.png)

The issue seems to be coming from this class **AuthorizeNet. Environment.GetProperty()** ([https://github.com/AuthorizeNet/sdk-dotnet/blob/master/Authorize.NET/Environment.cs](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAuthorizeNet%2Fsdk-dotnet%2Fblob%2Fmaster%2FAuthorize.NET%2FEnvironment.cs&data=04%7C01%7Cschandan%40ssactivewear.com%7Cb3c60752d7c2437c806108d9e674b0e3%7C900126a2a1cc4953b1b84c064100d27d%7C0%7C0%7C637794211146372021%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tCpauY1xCdS9WKNcjWwoMxKGiWV%2B%2Bc4kyC6yIsseie0%3D&reserved=0))
When the app is getting recycled or deployed , the  ConfigurationManager.AppSettings native object is in the process of getting populated with appsettings propery from Web.config file , 
Since it is a NameValue collection , (which is  not ThreadSafe )if  any other process tried to read the ConfigurationManager.AppSettings.**AllKeys** , the below exception is  thrown .
And the Problem with Static attributes is that if gets corrupted due to an error  , the only way to fix that is by getting app pool restarted

![image](https://user-images.githubusercontent.com/98968474/152376735-66a719d8-ed76-41d5-8b0c-a9ea4d2c8bf7.png)

![image](https://user-images.githubusercontent.com/98968474/152376757-9c703fe7-65aa-40ea-9745-eb5b83414c4a.png)

### **Proposed Fix:**
Please let us know if there is a way to get around this issue . If not this is what we tried and it seems if you make this change in the Environment.cs File it might work
We tested by bombarding requests the below snippet of code when the app is getting recycled , an error gets thrown when the “ConfigurationManager.AppSettings.**AllKeys**” gets invoked.
Microsoft documentation says it’s a NamedValue collection by design (which is not thread safe). Hence when other process is trying to access it when it is written it throws an error 

![image](https://user-images.githubusercontent.com/98968474/152376811-5ba9b6f1-5171-44d2-9f4c-11fdf8035196.png)

We tried this snippet and bombarded with similar load and it seems to do the  trick as it doesn’t access **AllKeys** variable and right after we added the snippet that is similar to Environment.CS file and it fails

![image](https://user-images.githubusercontent.com/98968474/152376871-a965a1bf-42bf-4ab5-a627-7ddc947db31a.png)

### **Conclusion** :
Changing the way ConfigurationManager.AppSettings is read might fix the issue (By not accessing AllKeys)
Or Please let us know if there is a different way to handle this issue

**Comment by gnongsie** [comment]
This fix has been incorporated, along with a more standard mutex lock, in v2.0.3.

@schandan-ssactivewear : Kindly validate the fix and close this issue if you are satisfied.

**Comment by schandan-ssactivewear** [comment]
Thanks so much  @gnongsie .
will check and let you know.

**Comment by dstelangre** [comment]
@gnongsie I am facing  same issue , I am using AuthorizeNet version 2.0.3

The type initializer for 'AuthorizeNet.Util.HttpUtility' threw an exception.

**Comment by schandan-ssactivewear** [comment]
we haven't seen this problem since last 3 months after we started using  AuthorizeNet version 2.0.3.
Your cause of the issue seems different ,can you please share the entire stack trace.

**Comment by dstelangre** [comment]
Inner exception:

System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
File name: 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at AuthorizeNet.Environment.GetProperty(String propertyName)
   at AuthorizeNet.Environment.getBooleanProperty(String propertyName)
   at AuthorizeNet.Util.HttpUtility..cctor()
   
   Stack trace :
   
   at AuthorizeNet.Util.HttpUtility.GetPostUrl(Environment env)
   at AuthorizeNet.Util.HttpUtility.PostData[TQ,TS](Environment env, TQ request)
   at AuthorizeNet.Api.Controllers.Bases.ApiOperationBase`2.Execute(Environment environment)

**Comment by schandan-ssactivewear** [comment]
I might need more -are you seeing "**Index was outside the bounds of Array**" ?

![image](https://user-images.githubusercontent.com/98968474/172830796-a28dd016-2215-4619-8864-b980781de6c0.png)

**Comment by dstelangre** [comment]
I am not able to see that 

In class HttpUtility   , GetPostUrl method  at below line throwing error
 HttpUtility.Logger.debug(string.Format("Creating PostRequest Url: '{0}'", (object) postUrl));

**Comment by dstelangre** [comment]
I am not able to do single transaction due to this error , I am using NuGet package AuthorizeNet version 2.0.3

**Comment by extinctsion** [comment]
We can eliminate this issue by installing System.Net.Http.Formatting.Extension packet from the NuGet package manager. I hope it solves the issue.

**Comment by schandan-ssactivewear** [comment]
Sorry, it didn’t work. Maybe the cause of your error wasn’t due to thread conflict from multiple instances initializing at the same time.

**Comment by delviscovom** [comment]
I am seeing the same issue with version 2.0.3 .NET 7.0 

The type initializer for 'AuthorizeNet.Util.HttpUtility' threw an exception. Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
   
      at AuthorizeNet.Environment.GetProperty(String propertyName)
   at AuthorizeNet.Environment.getBooleanProperty(String propertyName)
   at AuthorizeNet.Util.HttpUtility..cctor()
