### ISSUE TITLE
NullReferenceException on GetTransactionDetails

### ISSUE THREAD

**Issue by dgw2jr** [AuthorizeNet/sdk-dotnet#30]
This issue occurs completely random. I pass a valid transaction id string to GetTransactionDetails and CheckForErrors throws a NullReferenceException.

Stack Trace:

   at AuthorizeNet.HttpXmlUtility.CheckForErrors(ANetApiResponse response) in c:\Users\dwoodfor\Downloads\sdk-dotnet-master\sdk-dotnet-master\Authorize.NET\Utility\HttpXmlUtility.cs:line 99
   at AuthorizeNet.HttpXmlUtility.Send(ANetApiRequest apiRequest) in c:\Users\dwoodfor\Downloads\sdk-dotnet-master\sdk-dotnet-master\Authorize.NET\Utility\HttpXmlUtility.cs:line 80
   at AuthorizeNet.ReportingGateway.GetTransactionDetails(String transactionID) in c:\Users\dwoodfor\Downloads\sdk-dotnet-master\sdk-dotnet-master\Authorize.NET\Reporting\ReportingGateway.cs:line 121
   at NutraCardWeb.Controllers.TransactionController.Get(String id) in c:\Users\dwoodfor\Documents\Visual Studio 2012\Projects\NutraCardWeb\NutraCardWeb\Controllers\TransactionController.cs:line 30
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)

**Comment by brianmc** [comment]
Closing this one as we have not seen any further reports.  Feel free to reopen or open a new bug if there are more repro details.

Thanks.
